language: python

sudo: false

os:
  - linux

python:
  - "3.8"

env:
  global:
    - GITHUB_APP_INTEGRATION_ID=1234
    - GITHUB_APP_PRIVATE_KEY=abcd

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - pytest -rx --flake8 --cov astropy_bot astropy_bot
  - python run.py --skip-run
  - python -c "from baldrick.config import load; load('pyproject.toml', tool='astropy-bot')"

after_success:
  - codecov
